accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login, logout
from . import views

urlpatterns = [
    url(r'^login/$', login, name='login'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
]

blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<pk>\d+)/$', views.detail, name='detail'),

]

practice3/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    photo = models.FileField(default="")
    view = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post)
    message = models.TextField()
    commenter = models.ForeignKey(settings.AUTH_USER_MODEL)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

blog/forms.py
from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'photo', 'content']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['message']

accounts/views.py
from django.conf import settings
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import redirect, render


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(settings.LOGIN_URL)
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup_form.html', {
        'form': form,
    })

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment

# Create your views here.

def index(request):
    post_list = Post.objects.all()
    return render(request, 'blog/index.html', {'post_list':post_list})

def detail(request, pk):
    post_detail = get_object_or_404(Post, pk=pk)
    post_detail.view += 1
    post_detail.save()
    return render(request, 'blog/detail.html', {'post_detail':post_detail})

def post_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            messages.success(request, '글이 생성됐습니다.')
            return redirect(reverse('blog:detail', args=[post.pk]))
    else:
        form = PostForm()
    return render(request, 'blog/post_form.html', {'form': form})

accounts/templates/accounts/signup_form.html
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" />
</form>

blog/templates/blog/detail.html
<div class="row">
    <a href="{% url 'blog:index' %}">목록으로</a>
    <h1>{{ post_detail.title }}</h1>
    조회수: {{ post_detail.view }}<br>
    작성자: {{ post_detail.author }}<br>
    생성일: {{ post_detail.created_at }}<br>
    수정일: {{ post_detail.updated_at }}<hr/>
    <img src="{{ post_detail.photo.url }}"/><hr/>
    {{ post_detail.content }}<br><hr/>
    <div>
        <h2>덧글</h2>
        {% if post_detail.comment_set.all %}
            {% for comment in post_detail.comment_set.all %}
                <li>
                    {{ comment.commenter }}: {{ comment.message }}
                </li>
            {% endfor %}
        {% else %}
            <h3> 등록된 덧글이 없습니다 </h3>
        {% endif %}
    </div>
</div>

blog/templates/blog/index.html
{% for post in post_list %}
    <li>
        <h1><a href="{% url 'blog:detail' post.pk %}">{{ post.title }}</a> {{ post.view }}</h1>
    </li>
{% endfor %}

blog/templates/blog/post_form.html
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" />
</form>